name: Pull Request
on:
  pull_request:
    
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Install TF
        uses: hashicorp/setup-terraform@v2
      - uses: actions/checkout@v3
      - run: terraform fmt -recursive -check
